### ISSUE TITLE
In v0.3.2 the Round 1 in create-asset seems to break the node SDK

### ISSUE THREAD

**Issue by jorgego11** [hyperledger/caliper-benchmarks#109]
Running create-asset.yaml in v0.3.2 with Caliper Bind(ed) to Fabric v2.1.0  with UTC being IBP Fabric network with images at Fabric v2.1.1

In create-asset.yaml  all rounds are type: fixed-backlog except the first one (??!!) that its fixed-rate as shown below:

  - label: create-asset-8000-fixed-tps
    description: Test a submitTransaction() Gateway method against the NodeJS `fixed-asset` Smart Contract method named `createAsset`, which inserts an asset of size 8000 bytes into the World State database at a fixed TPS rate.
    chaincodeID: fixed-asset
    txDuration: 300
    rateControl: { type: fixed-rate, opts: { tps: 15} }
    arguments:
      chaincodeID: fixed-asset
      bytesize: 8000
    callback: benchmarks/api/fabric/lib/create-asset.js

I see two problems with this:
1) Why different rate controls in the same create-asset.yaml?
2) Round 1 in create-asset seems to breaks the node SDK with the error below.  If I remove this fixed-rate round and leave all the others which are fixed-backlog then everything runs fine. 

2020-08-12T23:14:43.294Z - error: [EventService]: send[ibp-jorge-peer11-peer.ibp25-dal10-jorge-bd8e586d66eff81119bfe4722b13dbd4-0000.us-south.containers.appdomain.cloud:443] - #1 - no targets started - Error: Event service ibp-jorge-peer11-peer.ibp25-dal10-jorge-bd8e586d66eff81119bfe4722b13dbd4-0000.us-south.containers.appdomain.cloud:443 is currently listening
2020-08-12T23:14:43.297Z - warn: [TransactionEventHandler]: strategyFail: commit failure for transaction "9bd982c0d86a54d5ba1f6a1b03dfc6596d32fa5f8abd1633e35be2762d9e963c": Error: No successful events received
(node:77242) UnhandledPromiseRejectionWarning: Error: No successful events received
at AnyForTxStrategy.checkCompletion (/Users/jorgego/Documents/CODE/caliper-benchmarks/caliper-benchmarks/node_modules/fabric-network/lib/impl/event/anyfortxstrategy.js:31:20)
at AnyForTxStrategy.errorReceived (/Users/jorgego/Documents/CODE/caliper-benchmarks/caliper-benchmarks/node_modules/fabric-network/lib/impl/event/transactioneventstrategy.js:61:14)
at TransactionEventHandler.eventCallback (/Users/jorgego/Documents/CODE/caliper-benchmarks/caliper-benchmarks/node_modules/fabric-network/lib/impl/event/transactioneventhandler.js:92:27)
at CommitListenerSession.start (/Users/jorgego/Documents/CODE/caliper-benchmarks/caliper-benchmarks/node_modules/fabric-network/lib/impl/event/commitlistenersession.js:27:18)
at process._tickCallback (internal/process/next_tick.js:68:7)
(node:77242) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:77242) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by aklenik** [comment]
@nklincoln Any insights? 🤔

**Comment by jorgego11** [comment]
@nklincoln @aklenik 

I have found that lowering the TPS fixes the problem. For example,  _rateControl: { type: fixed-rate, opts: { tps: 10} }_ works fine.  (tps changed from 15 to 10 ) Therefore, the error seems to be related to some kind of resource over-utilization that creates time-outs in my network. 

**I still have the first question:**  Why different rate controls in the same create-asset.yaml?    Was this a typo?

**Comment by jorgego11** [comment]
opening the question on a separate issue.

**Comment by hoang-tranviet** [comment]
FYI, I still encounter exactly the same issue with v0.4.2.
